before_script:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - nvm install v10.11.0
  - nvm use v10.11.0
  - node --version
language: java
sudo: false
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - $HOME/.m2
os: linux
addons:
  hosts:
    - localhost
  chrome: stable
  apt:
    packages:
    - libgconf-2-4
script:
  - git fetch origin master
  - npm install -g @angular/cli
  - npm install
  - npm run e2e --headless
  - npm run build:packages
  - npm run lint
jobs:
  include:
    - stage: Release fix
      dist: trusty
      os: linux
      language: ruby
      if: type = push AND branch = master AND commit_message !~ /@RELEASE_MINOR/ AND commit_message !~ /@SKIP_RELEASE/ AND commit_message !~ /^v[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}$/
      script:
        - git checkout master && git reset --hard $sha1
        - git config --global user.email "travis@travis-ci.org" && git config --global user.name "Travis CI"
        - git remote remove origin
        - git remote add origin https://${GH_TOKEN}@github.com/groupdocs-total/GroupDocs.Total-Angular.git > /dev/null 2>&1
        - git fetch
        - git branch --set-upstream-to=origin/master master
        - echo "releasing fix"
        - npm install -g npx
        - npm install
        - npm run build:packages
        - git add dist
        - git commit -am "Build new version" || true
        - git status
        - npx lerna publish patch --yes
        - git status
    - stage: Release minor update
      dist: trusty
      os: linux
      language: ruby
      if: type = push AND branch = master AND commit_message =~ /@RELEASE_MINOR/ AND commit_message !~ /@SKIP_RELEASE/ AND commit_message !~ /^v[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}$/
      script:
        - git checkout master && git reset --hard $sha1
        - git config --global user.email "travis@travis-ci.org" && git config --global user.name "Travis CI"
        - git remote remove origin
        - git remote add origin https://${GH_TOKEN}@github.com/groupdocs-total/GroupDocs.Total-Angular.git > /dev/null 2>&1
        - git fetch
        - git branch --set-upstream-to=origin/master master
        - echo "releasing minor update"
        - npm install -g npx
        - npm install
        - npm run build:packages
        - git add dist
        - git commit -am "Build new version" || true
        - git status
        - npx lerna publish minor --yes
        - git status
